"""
Django settings for menu_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# .env 파일 로드 (루트 폴더 .env 또는 백엔드 폴더 .env 순서로 확인)
root_env = Path(__file__).resolve().parent.parent.parent.parent / '.env'
backend_env_local = Path(__file__).resolve().parent.parent.parent / '.env.local'
backend_env = Path(__file__).resolve().parent.parent.parent / '.env'

if os.path.exists(root_env):
    load_dotenv(root_env)
elif os.path.exists(backend_env_local):
    load_dotenv(backend_env_local)
else:
    load_dotenv(backend_env)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY must be set in environment variables")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF trusted origins from environment variable
CSRF_TRUSTED_ORIGINS = [
    origin.strip() 
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') 
    if origin.strip()
]

# X-Frame-Options 설정
X_FRAME_OPTIONS = 'SAMEORIGIN'

# 보안 헤더 설정
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# HTTPS 보안 설정
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Sentry (프로덕션 에러/성능 모니터링)
# SENTRY_DSN이 없으면 init을 건너뛴다 → 로컬/스테이징은 자동 비활성.
SENTRY_DSN = os.environ.get('SENTRY_DSN')
if SENTRY_DSN:
    try:
        import sentry_sdk

        def _sentry_before_send(event, hint):
            # 봇이 잘못된 Host 헤더로 접근할 때 나는 DisallowedHost는 무시한다.
            exc_info = hint.get('exc_info')
            if exc_info and exc_info[0].__name__ == 'DisallowedHost':
                return None
            # error/fatal 이벤트는 Discord 에러 웹훅으로도 알린다(best-effort).
            # 알림 발송 실패 로그(menu.notifications)는 제외해 무한루프를 막는다.
            if event.get('level') in ('error', 'fatal') and event.get('logger') != 'menu.notifications':
                try:
                    from menu.notifications import send_error_alert
                    send_error_alert(event, hint)
                except Exception:
                    pass
            return event

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
            traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
            profiles_sample_rate=float(os.environ.get('SENTRY_PROFILES_SAMPLE_RATE', '0.0')),
            send_default_pii=False,
            before_send=_sentry_before_send,
        )
    except Exception:
        # Sentry 초기화 실패가 앱 기동을 막지 않도록 한다.
        pass


# Application definition

INSTALLED_APPS = [
    'menu',
    'rest_framework',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'menu.middleware.RestaurantMiddleware',
    # request.restaurant 를 읽으므로 반드시 위 미들웨어 뒤에 온다
    'menu.middleware.SubscriptionGateMiddleware',
]

ROOT_URLCONF = 'menu_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'menu_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 로컬 개발용 SQLite 사용
if os.environ.get('USE_SQLITE') == 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # 안전장치: DB_NAME 미설정 시 기동 실패시킨다.
    # (미설정 시 다른 프로젝트의 운영 DB로 오연결되어 손상시킬 수 있으므로 기본값을 두지 않는다)
    _db_name = os.environ.get('DB_NAME')
    if not _db_name:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            'DB_NAME 환경변수가 설정되지 않았습니다. 운영/개발 DB 오연결 방지를 위해 '
            'DB_NAME을 명시적으로 지정해야 합니다.'
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_name,
            'USER': os.environ.get('DB_USER', 'bidbar_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

    # 개발 환경 전용: seed_from_prod 명령이 운영 DB를 읽기 위한 보조 연결.
    # PROD_DB_NAME 이 설정된 경우에만 추가된다(운영 서버에는 설정하지 않는다).
    _prod_db_name = os.environ.get('PROD_DB_NAME')
    if _prod_db_name:
        DATABASES['prod'] = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _prod_db_name,
            'USER': os.environ.get('PROD_DB_USER', 'bar_user'),
            'PASSWORD': os.environ.get('PROD_DB_PASSWORD', ''),
            'HOST': os.environ.get('PROD_DB_HOST', 'localhost'),
            'PORT': os.environ.get('PROD_DB_PORT', '5432'),
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise 설정 (프로덕션 정적 파일 서빙)
#
# STATICFILES_STORAGE 로 지정하면 안 된다. 그 설정은 Django 4.2 에서 폐기되고
# 5.1 에서 제거됐다 — 제거된 설정은 에러를 내지 않고 그냥 무시된다. 그래서
# 해싱이 꺼진 채로 배포가 초록불이었고, 파일 이름이 그대로인데 응답에는
# cache-control: max-age=2592000(30일) 이 붙어 나갔다. CSS 를 고쳐도 사장님
# 브라우저는 최대 30일 동안 옛 화면을 본다. 2026-08-23 에 실제로 그 상태를
# 만났다.
#
# Manifest 저장소는 파일 이름에 내용 해시를 붙인다(admin.a1b2c3d4.css).
# 내용이 바뀌면 이름이 바뀌므로 캐시가 길어도 배포가 즉시 보인다.
if not DEBUG:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',
    },
}

# CORS 설정 (FE에서 API 호출 허용)
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True


# 구독이 끝난 매장의 손님 화면을 잠글지. 결제 대행사가 붙어서 사장님이
# 실제로 돈을 낼 수 있게 된 다음에 켠다. 그 전에 켜면 체험이 끝난 매장은
# 되살릴 방법 없이 메뉴판만 꺼진다.
ENFORCE_SUBSCRIPTION = os.environ.get('ENFORCE_SUBSCRIPTION', 'False') == 'True'


# 결제 화면의 이의신청 창구와 이용약관 주소.
#
# 전자결제 심사는 결제 화면에 취소·이의신청 방법이 안내돼 있는지 본다.
# 연락처의 원본은 frontend/src/lib/business.ts 이고(사이트 하단 정보와 같은
# 값이어야 한다), 여기 값이 그것과 갈리지 않는지는 tests_pricing 이 대조한다.
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', '')
SUPPORT_PHONE = os.environ.get('SUPPORT_PHONE', '')

# 마케팅 사이트(Vercel)의 이용약관. 결제 화면에서 새 창으로 연다.
MARKETING_SITE_URL = os.environ.get(
    'MARKETING_SITE_URL', 'https://bar-menu.ddnsfree.com'
).rstrip('/')
TERMS_URL = f'{MARKETING_SITE_URL}/terms'


# ── 카카오페이 ────────────────────────────────────────────────────────
# 개발용 Secret key 만 있으면 계약 전에도 전 구간을 시험할 수 있다.
# 테스트 CID: 정기결제 TCSUBSCRIP / 단건 TC0ONETIME (문서 명시)
KAKAOPAY_SECRET_KEY = os.environ.get('KAKAOPAY_SECRET_KEY', '')
KAKAOPAY_CID = os.environ.get('KAKAOPAY_CID', '')
