# Generated by Django 5.2.7 on 2026-02-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='intro_image',
            field=models.ImageField(blank=True, help_text='메인 페이지에 표시될 인트로 이미지', null=True, upload_to='site_images/', verbose_name='인트로 이미지'),
        ),
    ]
