# Generated by Django 5.2.7 on 2026-02-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_alter_sitesettings_intro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='파비콘(Favicon)으로 사용될 로고 이미지', null=True, upload_to='site_images/', verbose_name='로고 이미지'),
        ),
    ]
