# Generated by Django 5.2.7 on 2026-06-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_alter_menuitem_description_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='click_expand',
            field=models.BooleanField(default=False, help_text='체크하면 이미지 클릭 시 라이트박스로 확대됩니다', verbose_name='이미지 클릭 확대'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='detail_description',
            field=models.TextField(blank=True, help_text='상세 모달에 표시될 상세 설명 (미설정 시 기본 설명 사용)', null=True, verbose_name='상세보기 설명'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='detail_image',
            field=models.ImageField(blank=True, help_text='상세 모달에 표시될 이미지 (미설정 시 기본 메뉴 이미지 사용)', null=True, upload_to='menu_images/detail/', verbose_name='상세보기 이미지'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_mode',
            field=models.CharField(choices=[('auto', '자동 (이미지 있으면 이미지만, 없으면 텍스트만)'), ('image_only', '이미지만 표시'), ('text_only', '텍스트만 표시'), ('combined', '이미지 + 텍스트 (좌측 이미지, 우측 텍스트)')], default='auto', help_text='메뉴 카드의 표시 방식을 선택합니다', max_length=20, verbose_name='표시 모드'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='enable_detail_view',
            field=models.BooleanField(default=False, help_text='체크하면 메뉴 클릭 시 상세 정보 모달이 표시됩니다', verbose_name='상세보기 활성화'),
        ),
    ]
