# Generated by Django 5.2.7 on 2026-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_menuitempairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_description_bold',
            field=models.BooleanField(default=False, verbose_name='페어링 설명 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_description_color',
            field=models.CharField(blank=True, default='', help_text='#888888', max_length=7, verbose_name='페어링 설명 색상'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_description_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='페어링 설명 폰트 파일'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_description_italic',
            field=models.BooleanField(default=False, verbose_name='페어링 설명 이탤릭'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_description_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 11)', null=True, verbose_name='페어링 설명 크기'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_name_bold',
            field=models.BooleanField(default=False, verbose_name='페어링명 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_name_color',
            field=models.CharField(blank=True, default='', help_text='#ffffff', max_length=7, verbose_name='페어링명 색상'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_name_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='페어링명 폰트 파일'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_name_italic',
            field=models.BooleanField(default=False, verbose_name='페어링명 이탤릭'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_name_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 14)', null=True, verbose_name='페어링명 크기'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_price_bold',
            field=models.BooleanField(default=False, verbose_name='페어링 가격 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_price_color',
            field=models.CharField(blank=True, default='', help_text='#ffffff', max_length=7, verbose_name='페어링 가격 색상'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_price_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='페어링 가격 폰트 파일'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_price_italic',
            field=models.BooleanField(default=False, verbose_name='페어링 가격 이탤릭'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pairing_price_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 12)', null=True, verbose_name='페어링 가격 크기'),
        ),
    ]
