# Generated by Django 5.2.7 on 2026-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0036_sitesettings_pairing_description_bold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름(업체명)')),
                ('contact_info', models.CharField(max_length=200, verbose_name='연락처 또는 이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수 일시')),
            ],
            options={
                'verbose_name': '제휴 문의',
                'verbose_name_plural': '제휴 문의 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
