# Generated by Django 5.2.7 on 2026-07-01 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0038_contactsubmission_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_payhere',
            field=models.BooleanField(default=False, verbose_name='페이히어 결제 활성화'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_wifi',
            field=models.BooleanField(default=False, verbose_name='WiFi 안내 활성화'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WiFi 비밀번호'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wifi_security',
            field=models.CharField(choices=[('WPA', 'WPA/WPA2'), ('WEP', 'WEP'), ('nopass', 'Open')], default='WPA', max_length=20, verbose_name='WiFi 보안 설정'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wifi_ssid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WiFi SSID'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(default='테이블', max_length=50, verbose_name='테이블 번호')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('cancelled', '취소됨')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('total_price', models.IntegerField(default=0, verbose_name='총 결제금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경 시간')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menu.restaurant', verbose_name='가게')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='메뉴명')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitem', verbose_name='메뉴')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 상세 항목',
                'verbose_name_plural': '주문 상세 항목 목록',
            },
        ),
    ]
