# Generated by Django 5.2.7 on 2026-07-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0039_sitesettings_enable_payhere_sitesettings_enable_wifi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payhere_api_key',
            field=models.CharField(blank=True, help_text='페이히어 POS 연동 API Key', max_length=200, null=True, verbose_name='페이히어 API Key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payhere_store_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='페이히어 상점 ID'),
        ),
    ]
