# Generated by Django 5.2.7 on 2026-07-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0040_sitesettings_payhere_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='restrict_by_ip',
            field=models.BooleanField(default=False, help_text='체크 시 설정된 매장 공인 IP에서 접속하지 않은 고객의 접속을 제한합니다.', verbose_name='매장 WiFi(IP) 접속 제한 활성화'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_public_ip',
            field=models.CharField(blank=True, help_text='매장의 공인 IP 주소 (예: 123.45.67.89)', max_length=100, null=True, verbose_name='매장 공인 IP 주소'),
        ),
    ]
