# Generated by Django 5.2.7 on 2026-07-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0041_sitesettings_restrict_by_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='restrict_by_wifi_ssid',
            field=models.BooleanField(default=False, help_text='체크 시 테이블 QR 코드로 접속하지 않았거나 매장 와이파이 SSID 정보가 다르면 접속을 제한합니다.', verbose_name='매장 WiFi SSID 접속 제한 활성화'),
        ),
    ]
