# Generated by Django 5.2.7 on 2026-07-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0042_sitesettings_restrict_by_wifi_ssid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='disable_screenshots',
            field=models.BooleanField(default=False, help_text='활성화 시 고객 메뉴판 사이트에서 스크린샷 및 화면 캡쳐(프린트 등)를 방지합니다.', verbose_name='스크린샷 금지 활성화'),
        ),
    ]
