# Generated by Django 5.2.7 on 2026-07-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0043_sitesettings_disable_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_cart',
            field=models.BooleanField(default=False, help_text='체크 시 고객 메뉴판 사이트에서 장바구니 추가 버튼 및 장바구니 버튼이 표시됩니다.', verbose_name='장바구니 활성화'),
        ),
    ]
