# Generated by Django 5.2.7 on 2026-07-04 09:39

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0044_sitesettings_enable_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='category_card_layout_json',
            field=models.JSONField(blank=True, default=menu.models.default_category_layout, help_text='카테고리 카드의 컴포넌트 배치 및 보임 설정 JSON', verbose_name='카테고리 카드 레이아웃 JSON'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_card_layout_json',
            field=models.JSONField(blank=True, default=menu.models.default_menu_layout, help_text='메뉴 카드의 컴포넌트 배치 및 보임 설정 JSON', verbose_name='메뉴 카드 레이아웃 JSON'),
        ),
    ]
