# Generated by Django 5.2.7 on 2026-08-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0045_sitesettings_category_card_layout_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('entry', 'Entry'), ('pro', 'Pro'), ('premium', 'Premium')], default='entry', max_length=20, verbose_name='요금제')),
                ('status', models.CharField(choices=[('trialing', '무료 체험'), ('active', '이용 중'), ('past_due', '결제 실패'), ('canceled', '해지')], default='trialing', max_length=20, verbose_name='상태')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='체험 종료')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='이번 결제 주기 종료')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='해지 시각')),
                ('provider', models.CharField(blank=True, default='', max_length=30, verbose_name='결제 대행사')),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=200, verbose_name='대행사 고객 ID')),
                ('provider_subscription_id', models.CharField(blank=True, default='', max_length=200, verbose_name='대행사 구독 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='menu.restaurant', verbose_name='매장')),
            ],
            options={
                'verbose_name': '구독',
                'verbose_name_plural': '구독 목록',
            },
        ),
    ]
