# Generated by Django 5.2.7 on 2026-08-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0046_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='trial_ends_at',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('unpaid', '미결제'), ('active', '이용 중'), ('past_due', '결제 실패'), ('canceled', '해지'), ('partner', '무제한 파트너')], default='unpaid', max_length=20, verbose_name='상태'),
        ),
    ]
