# Generated by Django 5.2.7 on 2026-08-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0048_existing_restaurants_become_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_tid',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='진행 중 결제 번호'),
        ),
    ]
