# Generated by Django 5.2.7 on 2026-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0049_subscription_pending_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', '무료 체험'), ('unpaid', '미결제'), ('active', '이용 중'), ('past_due', '결제 실패'), ('canceled', '해지'), ('partner', '무제한 파트너')], default='unpaid', max_length=20, verbose_name='상태'),
        ),
    ]
