# Generated by Django 5.2.7 on 2026-08-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0050_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='연락처'),
        ),
    ]
