# Generated by Django 5.2.7 on 2026-09-12 13:52

from django.db import migrations, models


def trialing_becomes_unpaid(apps, schema_editor):
    """
    남아 있는 체험 매장을 미결제로 내린다.

    상태로만 고른다. 날짜로 고르면 옛 결제일을 달고 있는 파트너·해지 매장이
    딸려 들어와 영업 중인 가게가 꺼진다.

    current_period_end 도 비운다. 남겨 두면 is_usable 의 마지막 날짜 분기로
    떨어져, 체험이 끝난 매장이 상태만 unpaid 인 채 계속 열려 있다.
    """
    Subscription = apps.get_model('menu', 'Subscription')
    Subscription.objects.filter(status='trialing').update(
        status='unpaid', current_period_end=None
    )


def unpaid_stays_unpaid(apps, schema_editor):
    """되돌릴 것이 없다. 체험이 폐지됐으므로 trialing 으로 되살리지 않는다."""


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0053_owner_admin_group'),
    ]

    operations = [
        # AlterField 보다 먼저 돌아야 한다. choices 에서 trialing 이 빠진 뒤에
        # 옮기려 하면 고를 값이 없다.
        migrations.RunPython(trialing_becomes_unpaid, unpaid_stays_unpaid),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('unpaid', '미결제'), ('active', '이용 중'), ('past_due', '결제 실패'), ('canceled', '해지'), ('partner', '무제한 파트너')], default='unpaid', max_length=20, verbose_name='상태'),
        ),
    ]
