# Generated by Django 5.2.7 on 2026-09-13 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0054_remove_trialing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('entry', 'Entry'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20, verbose_name='요금제')),
                ('depositor_name', models.CharField(max_length=50, verbose_name='입금자명')),
                ('amount', models.PositiveIntegerField(verbose_name='입금액')),
                ('status', models.CharField(choices=[('pending', '확인 대기'), ('confirmed', '확인됨'), ('rejected', '반려')], default='pending', max_length=20, verbose_name='상태')),
                ('note', models.TextField(blank=True, default='', verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청 일시')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 일시')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='확인한 사람')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='menu.restaurant', verbose_name='매장')),
            ],
            options={
                'verbose_name': '입금 신청',
                'verbose_name_plural': '입금 신청 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
