# Generated by Django 5.2.7 on 2026-09-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0055_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='photo_import_count',
            field=models.PositiveIntegerField(default=0, verbose_name='사진 등록 사용 횟수'),
        ),
    ]
