# Generated by Django 5.2.7 on 2026-09-25 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0056_subscription_photo_import_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='category_name_en_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='카테고리명(영문) 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_name_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='카테고리명(한글) 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='intro_video',
            field=models.FileField(blank=True, help_text='첫 번째로 표시될 로딩 비디오 (MP4 파일)', null=True, upload_to='site_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v'])], verbose_name='로딩 비디오'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='loading_video_2',
            field=models.FileField(blank=True, help_text='첫 번째 로딩 비디오 이후 재생될 두 번째 로딩 비디오 (화면 터치 시 스킵 가능)', null=True, upload_to='site_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v'])], verbose_name='로딩 비디오2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_description_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='메뉴 설명 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_name_en_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='메뉴명(영문) 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_name_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='메뉴명(한글) 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_notes_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='기타 사항 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_price_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='가격 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pairing_description_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='페어링 설명 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pairing_name_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='페어링명 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pairing_price_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['woff2', 'woff', 'ttf', 'otf'])], verbose_name='페어링 가격 폰트 파일'),
        ),
    ]
