# Generated by Django 5.2.7 on 2026-02-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_sitesettings_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#000000', help_text='사이트 배경색 (예: #000000)', max_length=20, verbose_name='배경색'),
        ),
    ]
