# Generated by Django 5.2.7 on 2026-02-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_sitesettings_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='category_card_color',
            field=models.CharField(default='#000000', help_text='카테고리 목록 카드의 배경색 (예: #000000)', max_length=20, verbose_name='카테고리 카드 배경색'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_card_color',
            field=models.CharField(default='#000000', help_text='메뉴 상세 항목의 배경색 (예: #000000)', max_length=20, verbose_name='메뉴 카드 배경색'),
        ),
    ]
