# Generated by Django 5.2.7 on 2026-03-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_sitesettings_category_card_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='loading_video_2',
            field=models.FileField(blank=True, help_text='첫 번째 로딩 비디오 이후 재생될 두 번째 로딩 비디오 (화면 터치 시 스킵 가능)', null=True, upload_to='site_videos/', verbose_name='로딩 비디오2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_manual_card',
            field=models.BooleanField(default=False, help_text='체크 시 메인 화면(인트로 이미지 밑)에 두 번째 로딩 비디오와 동일한 영상을 보여주는 카드가 표시됩니다.', verbose_name='메뉴 설명서 카드 표시'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='intro_video',
            field=models.FileField(blank=True, help_text='첫 번째로 표시될 로딩 비디오 (MP4 파일)', null=True, upload_to='site_videos/', verbose_name='로딩 비디오'),
        ),
    ]
