# Generated by Django 5.2.7 on 2026-04-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_sitesettings_loading_video_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='메뉴 설명'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.TextField(verbose_name='메뉴명'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name_en',
            field=models.TextField(blank=True, null=True, verbose_name='메뉴명(영문)'),
        ),
    ]
