# Generated by Django 5.2.7 on 2026-06-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_menuitem_click_expand_menuitem_detail_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='lightbox_style',
            field=models.CharField(choices=[('zoom', '확대 (기본) — 이미지가 중앙에서 확대됩니다'), ('slide_up', '슬라이드 — 아래에서 위로 올라옵니다'), ('fade', '페이드 — 서서히 나타납니다')], default='zoom', help_text='이미지 확대 시 애니메이션 스타일을 선택합니다', max_length=20, verbose_name='라이트박스 스타일'),
        ),
    ]
