# Generated by Django 5.2.7 on 2026-06-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_menuitem_lightbox_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='detail_description',
            field=models.TextField(blank=True, help_text='상세 모달(라이트박스)에 표시될 메뉴 세부 설명 및 주류 페어링 정보 (미설정 시 표시되지 않음)', null=True, verbose_name='메뉴 세부 설명'),
        ),
    ]
