# Generated by Django 5.2.7 on 2026-06-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_alter_menuitem_detail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='lightbox_opacity',
            field=models.IntegerField(default=35, help_text='배경 오버레이의 투명도(불투명도)를 설정합니다 (10% ~ 100%)', verbose_name='라이트박스 투명도 (%)'),
        ),
    ]
