# Generated by Django 5.2.7 on 2026-06-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_menuitem_lightbox_opacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='주류 이름')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pairing_images/', verbose_name='주류 이미지')),
                ('description', models.TextField(blank=True, null=True, verbose_name='주류 간단 설명')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='주류 가격')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='menu.menuitem', verbose_name='메뉴 항목')),
            ],
            options={
                'verbose_name': '추천 페어링',
                'verbose_name_plural': '추천 페어링',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
