# Generated by Django 5.2.7 on 2026-06-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0037_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='plan',
            field=models.CharField(default='general', max_length=50, verbose_name='선택 요금제'),
        ),
    ]
