[uwsgi]
project = menu_project
uid = ubuntu
base = /home/ubuntu/bar_menu/backend

chdir = %(base)/menu_project
home = %(base)/venv
module = %(project).wsgi:application

master = true
processes = 4

socket = %(base)/menu_project/uwsgi.sock
chmod-socket = 660
vacuum = true

die-on-term = true
logto = /home/ubuntu/bar_menu/backend/menu_project/uwsgi.log
