name: Deploy to Server

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd ~/bar_menu
          git fetch origin main
          git reset --hard origin/main
          source ~/bar_menu/venv/bin/activate
          pip install -q -r backend/requirements.txt
          cd backend/menu_project
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
          sudo systemctl restart bidbar

